spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/fishingfishing
    username: aa
    password: 'b'
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
mvc:
  path match:
    matching-strategy: ant_path_matcher

logging.level:
  org.hibernate.SQL: debug

jwt:
  secret: "fishingfishingsecretKey"


server:
  servlet:
    encoding:
      charset: UTF-8